### ISSUE TITLE
Stast

### ISSUE THREAD

**Issue by joywebpro** [299Ko/299ko#13]
Bonjour, 
Je suis pas trop pour google stat, 
donc d'ici prochainement, feras tu , une page Statistique ?
en séparant les robots, humains, ect .......
Cordialement

**Comment by MaxenceCauderlier** [comment]
Bonsoir @joywebpro 
Moi non plus je n'aime pas trop Google, mais c'est la solution de facilité. Me concernant, je n'ai aucune information de statistique sur aucun site, mais je sais que ça manque.
Malheureusement, c'est un peu long à implémenter si on veut faire un vrai truc.
Qu'est-ce que tu souhaiterais savoir à propos de tes visiteurs ?

**Comment by joywebpro** [comment]
Bonsoir @MaxenceCauderlier ,
La base de tout, le nombre de visite, séparer les robots...
j'ai pas mal de cms qui propose les stats, sans trop de complexiter..

**Comment by MaxenceCauderlier** [comment]
Je regarderai ça quand j'aurai un peu le temps. Si tu as des liens pour me montrer ce que tu envisages, je t'avoue que ça m'aiderait.

**Comment by MaxenceCauderlier** [comment]
Le plugin est dispo ici : https://community.299ko.ovh/d/64-lightstats-des-statistiques-dans-299ko
