### ISSUE TITLE
position

### ISSUE THREAD

**Issue by joywebpro** [299Ko/299ko#14]
Re bonjour,
j'ai créé un nouveau design, 
le soucis c'est que les contents, sont tous en bas.
 les contents de sont pas a là suite de ` <?php show::mainTitle(); ?>?`
il y a une modif dans common?

**Comment by MaxenceCauderlier** [comment]
Re :)
Non je n'ai pas touché à cette partie.
Je ne vois pas du tout ce que tu veux dire, et sans code ni image ça va être compliqué à t'aider.

Si tu veux, tu peux nous rejoindre sur le [forum](https://community.299ko.ovh/), c'est plus convivial ;)

**Comment by joywebpro** [comment]
Alors c'est bon je viens de comprendre le problème.
les pluging sont en dehors de head, et footer. j'expliquerai mieux plus tard.. tu peux fermer le sujet ;)
