### ISSUE TITLE
Analytics and Co : Suppression de Google Analytics si le code est vide

### ISSUE THREAD

**Issue by t0m4s** [299Ko/299ko#5]
Salut,

je viens d'installer 299ko à l'instant.
A ma grande surprise (ouais, j'avais juste lu la page de description de framalibre, pas la doc de 299ko) je vois des traces de connection vers google-analytics, cloudflare et quelques autres joyeusetés.
Si je suis à la recherche d'un CMS simple et léger, c'est aussi pour que les utilisateurs de mon site ne soient pas suivis à la trace par qui que ce soit (à peine 10 minutes après la création de mon nom de domaine google analytics a déjà des infos sur ce dernier !!!).

J'ai fait le ménage (désactiver le module SEO qui est activé par défaut, télécharger les dépendances utilisées et modifier config.php et tinymce.php).
Je suis peut-être un peu psychorigide mais ce flicage permanent m'insupporte. Est-ce que ça vous intéresserait de faire un deuxième package "gafam-free" qui permette de créer un site internet qui ne fasse pas fuiter d'infos vers des entreprises extérieures ? Si oui, je suis volontaire pour le maintenir.
A noter qu'il serait aussi très simple de créer votre paquet pour qu'il soit "propre" dès le départ (oui, il ferait un peu plus de 300ko...) et de juste mettre un avertissement à l'activation du module SEO.

Merci de me dire si vous jugez ce sujet digne d'intérêt ou pas.

**Comment by MaxenceCauderlier** [comment]
Bonsoir @t0m4s ,

Tu as raison, dans la version actuelle 299Ko utilise Google Analytics même si un identifiant n'est pas enregistré, et ce n'est pas un comportement souhaité. Le code à faire évoluer n'est pas difficile pour cette partie, je vais essayer de faire ça la semaine prochaine.
Concernant les appels aux CDN, c'est surtout pour alléger le poids du CMS.
Pour rappel, 299Ko est la "suite / fork" de 99ko, qui est un CMS voulu le plus léger possible pour pouvoir héberger un blog sur un mini espace. Mais ton raisonnement est le bon, même si des appels à Google seront toujours présents dans les versions à venir pour ceux qui activent ces plugins (SEO et ReCaptcha). Mais le développement va dans ce sens, pour la v2 nous avons déjà supprimé quelques CDN tels que jQuery et normalize, et je pense que tu as raison de le souligner, il faut aller plus loin afin.
L'inconvénient est que les visiteurs n'auront pas l'avantage d'avoir certainement ces ressources déjà en cache dans le navigateur si on se passe des CDN, comme FancyApps.

Penses-tu qu'il faille aller à fond et tout héberger sur le site, donc se passer des CDN ? Personnellement, je suis assez orienté "libre" et ta remarque me conforte dans cette idée, mais est-ce le cas de tout le monde ?

Merci en tous cas, bonne soirée l'ami.

**Comment by t0m4s** [comment]
Salut et merci pour ton retour.

Pour ce qui est du poids du CMS, qu'on stocke les fichiers sur notre serveur ou qu'on les fasse venir d'un autre serveur, le résultat est le même pour l'utilisateur final en terme de ko transférés.
Et même si le CMS atteignait 1Mo avec les dépendances, c'est même pas à la taille d'une disquette. Il me semble que tous les serveurs disposent d'un espace de stockage suffisant pour supporter cette charge (en donnant cette fois à l'utilisateur final l'avantage de visiter un site "propre").

J'ai pas eu beaucoup de temps pour travailler là-dessus depuis le début de notre conversation, ça devrait aller mieux d'ici la fin de la semaine.
Voilà déjà de quoi apporter les modifications nécessaires à ton CMS, il reste à supprimer tous les fichiers inutiles et à réussir à faire fonctionner le thème _modern_ pour tinyMCE (je sais pas pourquoi mais une fois installé en local, si j'essaye de passer un thème à tinyMCE, l'éditeur ne s'affiche pas) :

Si t'es sous linux voilà quelques lignes qui te feront gagner 10 minutes.
Se placer dans le répertoire de 299ko puis :
```
mkdir dependencies
cd dependencies
wget https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css
wget https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js
wget https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.css
wget https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.umd.js
wget https://use.fontawesome.com/releases/v6.2.1/fontawesome-free-6.2.1-web.zip
unzip fontawesome-free-6.2.1-web.zip
rm fontawesome-free-6.2.1-web.zip
wget https://download.tiny.cloud/tinymce/community/tinymce_6.2.0.zip
unzip tinymce_6.2.0.zip
rm tinymce_6.2.0.zip
mkdir tinymce/js/tinymce/themes/modern
cd tinymce/js/tinymce/themes/modern
wget https://cdn.tiny.cloud/1/no-api-key/tinymce/4.9.11-104/themes/modern/theme.min.js
```

Ensuite il faut mettre à jour config.php :
```
define('NORMALIZE', ROOT . 'dependencies/normalize.min.css');
define('JQUERY', ROOT . 'dependencies/jquery.min.js');
define('FONTICON', ROOT . 'dependencies/fontawesome-free-6.2.1-web/css/all.min.css');
define('FANCYCSS', ROOT . "dependencies/fancybox.css");
define("FANCYJS", ROOT . "dependencies/fancybox.umd.js");
```

puis mettre à jour plugin/tinymce/tinymce.php :
```
function tinymceAdminHead() {
    echo "<script src='" . ROOT . "dependencies/tinymce/js/tinymce/tinymce.min.js'></script>
  <script>
  tinymce.init({
    selector: 'textarea.editor',
    plugins: [
      'advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker',
      'searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking',
      'save table contextmenu directionality emoticons template paste textcolor'
    ],
    toolbar: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | print preview media fullpage | forecolor backcolor emoticons',
  });
  </script>";
}
```

Effectivement, cette version brute de décoffrage ajoute plusieurs dizaine de Mo de dépendances.
Mais un petit coup de [baobab](https://doc.ubuntu-fr.org/baobab) et on va vite pouvoir faire le ménage.

**Comment by t0m4s** [comment]
Bon, le javascript et moi, ça fait au moins trois.

Je n'arrive pas à intégrer tinymce en local. En tout cas, pas avec le thème personnalisé ni avec l'intégralité des plugins que vous aviez choisi d'activer (plugins qui posent soucis = print, hr et paste, même en ayant téléchargé les fichiers correspondants).
En passant, un petit copier/coller d'un message d'avertissement. En plus de **print**, **hr**, **paste** et du theme **modern**, j'ai donc supprimé les 3 plugins suivants dans ma config de tinymce  :
```
The following deprecated features are currently enabled and have been removed in TinyMCE 6.0. These features will no longer work and should be removed from the TinyMCE configuration. See https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/ for more information.

Plugins:
- contextmenu
- spellchecker
- textcolor
```

Voilà une petite mise à jour du message précédent si tu veux tester là où je me suis arrêté :
Se placer dans le répertoire de 299ko puis télécharger toutes les dépendances :
```
mkdir dependencies
cd dependencies
wget https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css
wget https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js
wget https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.css
wget https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.umd.js
wget https://use.fontawesome.com/releases/v6.2.1/fontawesome-free-6.2.1-web.zip
unzip fontawesome-free-6.2.1-web.zip
rm ./fontawesome-free-6.2.1-web.zip
wget https://download.tiny.cloud/tinymce/community/tinymce_6.2.0.zip
unzip tinymce_6.2.0.zip
rm ./tinymce_6.2.0.zip
cd tinymce/js/tinymce/plugins
mkdir print
cd print
wget https://cdn.tiny.cloud/1/no-api-key/tinymce/4.9.11-104/plugins/print/plugin.min.js
mkdir ../hr
cd ../hr
wget https://cdn.tiny.cloud/1/no-api-key/tinymce/4.9.11-104/plugins/hr/plugin.min.js
mkdir ../paste
cd ../paste
wget https://cdn.tiny.cloud/1/no-api-key/tinymce/4.9.11-104/plugins/paste/plugin.min.js
mkdir ../../themes/modern
cd ../../themes/modern
wget https://cdn.tiny.cloud/1/no-api-key/tinymce/4.9.11-104/themes/modern/theme.min.js
cd ../../../../../../
```

Modification de common/config.php:
```
config.php :
define('NORMALIZE', ROOT . 'dependencies/normalize.min.css');
define('JQUERY', ROOT . 'dependencies/jquery.min.js');
define('FONTICON', ROOT . 'dependencies/fontawesome-free-6.2.1-web/css/all.min.css');
define('FANCYCSS', ROOT . "dependencies/fancybox.css");
define("FANCYJS", ROOT . "dependencies/fancybox.umd.js");
```

Modification de plugin/tinymce/tinymce.php :
```
function tinymceAdminHead() {
    echo "<script src='" . ROOT . "dependencies/tinymce/js/tinymce/tinymce.min.js'></script>
  <script>
  tinymce.init({
    selector: 'textarea.editor',
    plugins: 'advlist autolink link image lists charmap preview anchor pagebreak searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking save table directionality emoticons template',
    toolbar: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | print preview media fullpage | forecolor backcolor emoticons',
  });
  </script>";
}
```

Suppression des fichiers inutilisés de FontAwesome (20.8 Mo -> 1.0Mo). J'ai conservé tous les fichiers de fonte, j'ai pas pris le temps de regarder si vous en utilisiez une ou plusieurs donc on peut possiblement gagner encore quelques centaines de ko :
```
rm -fr ./dependencies/fontawesome-free-6.2.1-web/sprites
rm -fr ./dependencies/fontawesome-free-6.2.1-web/svgs
rm -fr ./dependencies/fontawesome-free-6.2.1-web/metadata
rm -fr ./dependencies/fontawesome-free-6.2.1-web/js
rm -fr ./dependencies/fontawesome-free-6.2.1-web/less
rm -fr ./dependencies/fontawesome-free-6.2.1-web/scss
mv ./dependencies/fontawesome-free-6.2.1-web/css/all.min.css ./dependencies/fontawesome-free-6.2.1-web/css/all.min.bak
rm ./dependencies/fontawesome-free-6.2.1-web/css/*.css
mv ./dependencies/fontawesome-free-6.2.1-web/css/all.min.bak ./dependencies/fontawesome-free-6.2.1-web/css/all.min.css
```
Je me pencherai sur la suppression des fichiers non utilisés de tinymce quand l'intégration sera ok.

**Comment by jackplux** [comment]
Holà vous deux, ;)

`Penses-tu qu'il faille aller à fond et tout héberger sur le site, donc se passer des CDN ?`

Pratique les CND mais si on peut s'en passer... ;)

MOi, ce que je regarde, c'est la vocation de 99ko/299ko. La légèreté, la rapidité et le reste.

**Comment by MaxenceCauderlier** [comment]
J'ai pas mal regardé les alternatives.
Font-awesome fait quasiment 22Mo. On est loin des quelques ko annoncés XD
Je pense que je ferai autrement, prendre les icônes de [Bootstrap](https://icons.getbootstrap.com/) ou alors créer moi-même une police avec quelques icônes nécessaires pour 299Ko.
Mais dans tous les cas oui, je vais supprimer les appels aux CDN pour la v2 de 299Ko, le projet pourra ainsi tourner en autonome et en local.

**Comment by t0m4s** [comment]
Salut,

> Font-awesome fait quasiment 22Mo. On est loin des quelques ko annoncés XD
Il ne faut pas se contenter de télécharger les dépendances, il faut faire le ménage dedans. FontAwesome c'est 21 Mo d'images qui ne sont pas utilisées dans votre projet. Comme je l'ai écris dans mon message précédent, j'ai réduit FontAwesome à 1Mo et on peut faire mieux :
- 100 ko de CSS
- 900 Ko de fichiers de fonte qu'on peut probablement réduire à 100 ko puisque je n'ai pas pris le temps de regarder si vous utilisiez plusieurs des fontes proposées par FontAwesome.

Désolé pour le temps de réponse, j'ai pas beaucoup de temps libre en ce moment.

**Comment by MaxenceCauderlier** [comment]
Quitte à utiliser une librairie d'icônes, autant la laisser complète afin que l'utilisateur puisse ajoute des icônes dans ses menus et son contenu.
Je suis en train de modifier l'administration en ce moment avec les icônes de Bootstrap : 1900 icônes en 3Mo.
Je pense que je laisserai comme ça, tant pis pour les 299ko annoncés ^^
